import React from 'react';

export function ComplianceOverviewChart() {
  const categories = [
    { label: 'Turnover Target', score: 92, target: 100, color: 'bg-emerald-500' },
    { label: 'Technical Experience', score: 88, target: 100, color: 'bg-blue-600' },
    { label: 'OISD Safety Standards', score: 75, target: 100, color: 'bg-amber-500' },
    { label: 'Cross-Doc Verification', score: 82, target: 100, color: 'bg-indigo-600' },
    { label: 'DigiLocker Record Match', score: 95, target: 100, color: 'bg-teal-500' },
  ];

  return (
    <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-xs">
      <div className="flex items-center justify-between mb-4">
        <div>
          <h3 className="text-sm font-bold text-slate-900">Requirement-wise Compliance Average</h3>
          <p className="text-xs text-slate-500">System evaluation across active bids for tender MOPNG-2026-001</p>
        </div>
        <span className="text-xs font-semibold text-slate-500 bg-slate-100 px-2.5 py-1 rounded">
          Tender ID: MOPNG-2026-001
        </span>
      </div>

      <div className="space-y-4">
        {categories.map((c) => (
          <div key={c.label}>
            <div className="flex justify-between text-xs font-semibold mb-1 text-slate-700">
              <span>{c.label}</span>
              <span className="font-mono text-slate-900">{c.score}% Avg Score</span>
            </div>
            <div className="w-full bg-slate-100 rounded-full h-2.5 overflow-hidden">
              <div
                className={`h-2.5 rounded-full ${c.color} transition-all duration-500`}
                style={{ width: `${c.score}%` }}
              />
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

export function RiskDistributionGraph() {
  const riskLevels = [
    { label: 'Low Risk (0-20)', count: 28, percent: 58, color: 'bg-emerald-500', text: 'text-emerald-700' },
    { label: 'Medium Risk (21-50)', count: 15, percent: 31, color: 'bg-amber-500', text: 'text-amber-700' },
    { label: 'High Risk (51+)', count: 5, percent: 11, color: 'bg-rose-500', text: 'text-rose-700' },
  ];

  return (
    <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-xs flex flex-col justify-between">
      <div>
        <div className="flex items-center justify-between mb-2">
          <h3 className="text-sm font-bold text-slate-900">Risk Assessment Distribution</h3>
          <span className="text-xs text-slate-400 font-mono">48 Total Bids</span>
        </div>
        <p className="text-xs text-slate-500 mb-4">Categorized by deterministic signal weights & cross-verification flags.</p>

        {/* Stacked bar */}
        <div className="w-full h-4 rounded-full overflow-hidden flex bg-slate-100">
          <div style={{ width: '58%' }} className="bg-emerald-500 h-full" title="Low Risk (58%)" />
          <div style={{ width: '31%' }} className="bg-amber-500 h-full" title="Medium Risk (31%)" />
          <div style={{ width: '11%' }} className="bg-rose-500 h-full" title="High Risk (11%)" />
        </div>

        <div className="mt-5 space-y-3">
          {riskLevels.map((r) => (
            <div key={r.label} className="flex items-center justify-between text-xs p-2 rounded-lg bg-slate-50 border border-slate-100">
              <div className="flex items-center gap-2">
                <span className={`w-3 h-3 rounded-full ${r.color}`} />
                <span className="font-medium text-slate-800">{r.label}</span>
              </div>
              <div className="flex items-center gap-2 font-mono">
                <span className={`font-bold ${r.text}`}>{r.count} Bids</span>
                <span className="text-slate-400">({r.percent}%)</span>
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="mt-4 pt-3 border-t border-slate-100 text-[11px] text-slate-400 flex items-center gap-1">
        <svg className="w-3.5 h-3.5 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <span>Generated by Deterministic Compliance & Cross-Document Engine</span>
      </div>
    </div>
  );
}
